### ISSUE TITLE
G Key is being triggered as Shift+G?

### ISSUE THREAD

**Issue by retronikk** [RoStrap/Input#10]

**Comment by Validark** [comment]
What code did you use?

**Comment by retronikk** [comment]
![image](https://user-images.githubusercontent.com/57027197/67627761-5fff1680-f817-11e9-9258-2625592714a2.png)
V works but G requires shift to be held for some reason

**Comment by Validark** [comment]
I can't reproduce. This probably has to do with your keyboard, OS, or Roblox. You could try using [this place](https://gist.github.com/Validark/f8b4778062e933692e0d2a010aad0865) to see if you have the same problem.

**Comment by retronikk** [comment]
Yep same problem the G wont print if I don't hold shift

**Comment by Validark** [comment]
Try placing `print("0", UserInputService:IsKeyDown(Enum.KeyCode.LeftShift));` in different parts of the code (change 0 to 1, 2, 3, etc).

- See if it says you are holding Shift down when you aren't pressing anything.
- See if it says you are holding Shift down when you are pressing G
- See if it says you are holding Shift down when you are pressing V
- See if it says you are holding Shift down when you are pressing Shift

**Comment by retronikk** [comment]
It's def on my end, It works fine in game but studio test bugs out I have no idea why this happens
