### ISSUE TITLE
Screenshot functionality should be a separate module

### ISSUE THREAD

**Issue by Validark** [RoStrap/Input#6]
While nice, it could break code, and should be removed or moved somewhere else.

Will fix tomorrow

**Comment by devSparkle** [comment]
"Tomorrow" @Validark 

What is this screenshot functionality? Can developers manually force a user to take a screenshot?

**Comment by Validark** [comment]
No, it was pressing "-" to turn off all UI. It's an old, not super compatible feature that was thrown in there.

Also, the last few days have been very very difficult for me, so I put this off. I did however release the Keys module as a replacement for UserInputService, so I think I'll end up just removing it from RoStrap and just keeping it up on my personal profile as a deprecated module someone can salvage if they so desire

**Comment by Validark** [comment]
While `UserInputService` had some good ideas, I think they're better captured in the new `Keys` Library

**Comment by devSparkle** [comment]
@Validark this feature has already been [added to ROBLOX](https://blog.roblox.com/2016/12/toggle-guis-onoff-upgraded-studio-output-window/) by default!

**Comment by Validark** [comment]
Yeah, the module was created the month before that article
